# this is my first Github Actions workflow!

name: Build Application

runs:
  using: composite

  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5

  - name: Install Poetry
    uses: snok/install-poetry@v1

  - name: Install dependencies using Poetry
    run: |
      poetry install
      poetry run make install
  shell: bash
