# this is my first Github Actions workflow!

name: App Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        # run: |
        #   curl -sSL https://install.python-poetry.org | python3 -
        #   echo "export PATH=$HOME/.local/bin:$PATH" >> $HOME/.bashrc
        #   source $HOME/.bashrc
        uses: snok/install-poetry@v1
        with:
          virtualenv: true

      - name: Load cache venv
        uses: actions/cache@v4
        id: cached-poetry-dependancies
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies using Poetry
        if: steps.cached-poetry-dependancies.outputs.cache-hit != 'true'
        run: poetry run make install

      - name: Lint with flake8
        run: poetry run make check
