# this is my first Github Actions workflow!

name: App Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        # uses: snok/install-poetry@v1
        
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          poetry --version  # Confirm Poetry is installed

      - name: Install dependencies using Poetry
        run: |
          poetry install
          poetry run make install

      - name: Lint with flake8
        run: poetry run make check
